#! /usr/bin/env php
<?php

require_once(dirname(__FILE__).'/clips_tool.php');

$tool = get_clips_tool();

$command = 'shell';

if(count($argv) >= 2) { // We have the command
	$command = $argv[1];
}

$tool->execute($command, $argv);
