version: "1.0.0"
author: Jack <guitarpoet@gmail.com>
subclass_prefix: MY
core_dir: core
config_dir: config
test_dir: tests
rules_dir: 
    - rules
    - application/rules
helper_dir:
    - helpers
    - application/helpers
command_dir:
    - Commands
model_dir: models
library_dir: libraries
resource_handler_dir: handlers
datasource_dir: DataSources
bundle_dir: application/messages
sass_folders: application/static/scss
image_dir:
    - application/static/img
    - application/upload/img
template_dir:
    - templates
    - application/views
    - application/templates
controller_dir: Controllers
filter_dir: Filters
form_config_dir: application/config/form
pagination_config_dir: application/config/pagination
cache_dir: application/cache
widget_dir: 
    - src/Clips/Widgets
    - application/Widgets
smarty_compile_dir: application/cache/smarty_template_c
smarty_config_dir: application/config/smarty
smarty_cache_dir: application/cache/smarty
test_data_dir: tests/data
resolutions: [480, 640, 720, 1280, 1440, 1280, 2880]
sass_plugins:
    - Sass\AutoConstruct
    - Sass\AutoResolution
peg_dir:
    - config/pegs
    - application/config/pegs
