################################################################################
#
# The {{widget}} Widget Configuration
#
# @generated by Clips Generate Command
#
################################################################################

author: {{author}}
date: {{date}}
version: {{version}}
name: {{widget}}
doc:
    {{doc}}
